- setup.py
Strictly the .git extension points at the git repo bundle, which is useful only for cloning the git repository. GitHub very kindly redirects browser requests for this URL to the HTML home page, but we should save GitHub the effort and point to the correct site.
> Remove .git from project URL.

- asciimatics/effects.py
Added the ability to specify a colour to use when drawing the Cog effect.
The new colour argument defaults to 7 which matches the default colour value for Screen.draw().
> Updated Cog effect to allow colour specification

- samples/contact_list.py
Fixed a small sql parameterization error in the contact_list sample which meant that it would fail for ids over 9. 
I just changed the get_contact() to use named parametrization to be inline with the other SQL functions.
> SQL parametrization fix to contact_list sample

- asciimatics/screen.py
A getter for the current scene has been added to the screen object. This is required for handling screen resizes when the main loop is run manually by clients using draw_next_frame.
Tests are still passing.
Closes #144.
> Add a read-only property for the current scene

- setup.cfg
Currently the `LICENSE` file isn't included in the distributed wheels.
> include license in wheels

- asciimatics/screen.py
- asciimatics/widgets.py
Eliminated the need to call wcwidth and wcswidth for non-unicode aware screens. This effect is inherited to frames, canvases, and widgets.
> Extended unicode awareness to widgets, canvas, and frames for reduced CPU overhead

- CHANGES.rst
- asciimatics/effects.py
- tests/test_effects.py
I wanted to be able to set my own star patterns, like `··xxx+++++xx···············` and thought it would be helpful. This also lets users extend the `Stars` class and select a random pattern from a set without having to create a new `_Star` class.
It's pretty simple, you don't have to accept it I just thought it might be useful for people
> variable star patterns

- asciimatics/screen.py
Fix for argument error to win32.event.WaitForSingleObject found on Windows 10 with Python 2.7.15.
Attempting to run samples/contact_list.py on Windows 10 with Python 2.7.15 without this fix results in the following error:
```
File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 2107, in wait_for_input
rc = win32event.WaitForSingleObject(self._stdin, timeout * 1000)
SystemError: ..\Objects\longobject.c:463: bad argument to internal function
```
Not sure if this is the right fix, or the best fix, but samples/contact_list.py runs after it is applied, as do all the tests in the tests directory.
> Windows screen interrupt error fix

- asciimatics/widgets.py
In frames which contain ListBox with visible scroll bar mouse events meant for other widgets can be ignored.
Return None if mouse event was processed by scroll bar instead of re-assigning event to True/False (result of _ScrollBar.process_event()). 
None
> Fix mouse events processing for _BaseListBox scroll bar

- doc/source/io.rst
Small typo in doc/source/io.rst, should read support instead of zupport.
Closes #237 
Typo
> Fix simple typo: zupport -> support

- doc/source/widgets.rst
Fix typo in "Displaying your UI" section's second code snippet
> Fix typo in docs

- doc/source/troubleshooting.rst
Docs for issue #245
I'll let you explain *why* this happens and why `asciimatics` cannot restore the theme itself!
> Add troubleshooting docs about color theme reset

- .gitignore
- samples/256colour.py
- samples/bars.py
- samples/basics.py
- samples/bg_colours.py
- samples/cogs.py
- samples/contact_list.py
- samples/credits.py
- samples/experimental.py
- samples/fire.py
- samples/fireworks.py
- samples/forms.py
- samples/images.py
- samples/interactive.py
- samples/julia.py
- samples/kaleidoscope.py
- samples/maps.py
- samples/noise.py
- samples/pacman.py
- samples/particles.py
- samples/plasma.py
- samples/quick_model.py
- samples/ray_casting.py
- samples/rendering.py
- samples/simple.py
- samples/terminal.py
- samples/top.py
- samples/treeview.py
- samples/xmas.py
Scripts should now be runnable with `./script.py`. This uses `#!/usr/bin/env python3` so python3 just needs to be on the path. (This lets it work both in Linux as well as in macOS when using `brew` or other third-party package manager.)
Added a few lines to .gitignore:
- `venv` -- for venv support
- `.eggs/` -- non-Windows `eggs/` directory.
- `asciimatics/version.py` -- file started out with a statement to not put it in version control, so it seemed an ommision.
- `*.log` -- At least one sample, when run, created a `.log` file. Logs are not normal things to check in.
I had these files created, but they were not checked in, and it seemed like they should never be checked in.
Closes #248 …
> Make scripts runnable in macOS and Linux

- asciimatics/renderers.py
- tests/test_renderers.py
Fill with spaces the shortest lines in the speech bubble text to correctly render the right wall of the box
When passing a multiline text to a Speech Bubble the **right wall** of the box is not render correctly, this happens when the line to render is shorter than the longest line
```
text = "WELCOME TO ASCIIMATICS\n" \
"My name is Aristotle Arrow.\n" \
"I'm here to help you learn ASCIImatics."
effects.append(Print(screen, SpeechBubble(text, tail='L'), 5, 10))
```
If we fill the shortest lines with white spaces we can render all right walls in the same position as the longest line
> Shorter lines are filled with spaces to have uniform speech bubble boxes

- asciimatics/renderers.py
- tests/test_renderers.py
Height of the speech bubbles that not have a tail
The way a render calculate the max height of its image its counting the lines in the image
`self._max_height = max(len(image), self._max_height)`
When constructing a speech bubble a new line is always added at the end of the bubble, whether or not it has a tail
```
bubble = "╭─" + "─" * max_len + "─╮\n"
for line in text.split("\n"):
filler = " " * (max_len - len(line))
bubble += "│ " + line + filler + " │\n"
bubble += "╰─" + "─" * max_len + "─╯\n"
```
the last `\n` increase the bubble size by one by creating a new empty line. The new line is needed only when there is a tail
> Fix speech bubble height

- README.rst
- appveyor.yml
- doc/source/intro.rst
- setup.py
Fix #275.
Replace out of date pypiwin32 dependency with pywin32.
Removed specific version pin in appveyor as well.
> update win32 dependence (#275)

- CHANGES.rst
- asciimatics/widgets/button.py
- tests/test_widgets.py
#300
A feature request to give Button objects a .text attribute
In the implementation, I created a shadow copy of the text so that retrieving the .text didn't include the chevrons.
> Give Button a .text attribute

- CHANGES.rst
- asciimatics/widgets/frame.py
- asciimatics/widgets/popupmenu.py
- requirements/dev.txt
- samples/frame_borders.py
- tests/test_widgets.py
None
Frame can now support a scroll bar without rendering a border. Frame.has_border and Frame.can_scroll are now independent of each other. This is a breaking change: Frame(has_border=False) now needs to be Frame(has_border=False, can_scroll=False) to get the same effect)
Updated Frame.move_to() to use self._canvas for consistency
> Change Frame to support scroll bars without a border

- asciimatics/widgets/layout.py
- requirements/dev.txt
- tests/test_widgets.py
One line change that adds "return widget" to the end of Layout's add_widget() method. This allows doing one-line layout and creation such as:
```
self.my_button = layout.add_widget(Button("My Button"), 1)
```
> Add "return widget" to Layout's add_widget() method to make chaining easier

- asciimatics/exceptions.py
- asciimatics/parsers.py
- asciimatics/renderers/players.py
- asciimatics/widgets/textbox.py
- doc/source/io.rst
There are small typos in:
- asciimatics/exceptions.py
- asciimatics/parsers.py
- asciimatics/renderers/players.py
- asciimatics/widgets/textbox.py
- doc/source/io.rst
Fixes:
- Should read `indices` rather than `indeces`.
- Should read `overridden` rather than `overriden`.
- Should read `detected` rather than `detetected`.
- Should read `data` rather than `datd`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- asciimatics/effects.py
- tests/test_effects.py
`Sprite` can't be drawn at frame one 
It implements speed parameter on `Sprite` just like it's done on the `Print` effect. Now we can draw at frame one using `speed=0` and also have better control on frame rate on sprite.
> Add speed parameter to Sprite effect

- CHANGES.rst
- asciimatics/widgets/popupmenu.py
- tests/test_widgets.py
The border provides a visual separation of the popup menu from the background. Making it easier to see against a cluttered background.
> Allow the PopupMenu to have a border
