peterbrittain/asciimatics

- asciimatics/screen.py
- tests/test_screen.py
> Set signals to previous state upon _CursesScreen close

- asciimatics/widgets.py
- tests/test_widgets.py
I found that on_select is missed for ListBox widget. It should be fixed 😄
> Add missed on_select for ListBox +documentation

- CHANGES.rst
- asciimatics/widgets.py
- samples/credits.py
- tests/test_widgets.py
Well, following my proclamation in https://github.com/peterbrittain/asciimatics/issues/154#issuecomment-397868927, I decided I better do something :)
Here's a first stab at contributing here.
Closes https://github.com/peterbrittain/asciimatics/issues/124.
> Expose a focussed widget property.

- .travis.yml
- doc/source/contributing.rst
- doc/source/index.rst
- requirements.txt
- requirements/base.txt
- requirements/dev.txt
Here's a stab at some contribution documentation (what I would have liked to see).
I also saw some errors when building the documentation, so we should add that to the CI.
> Add contribution documentation and sphinx to the CI

- asciimatics/widgets.py
- tests/test_widgets.py
Fixes #168 and shows symbolic links and targets in the file browser either as
`-- A link -> To a file`
`+- A link -> To a directory`
> Show symbolic links in FileBrowser

- asciimatics/widgets.py
- tests/test_widgets.py
> Attempt to solve macos file names

- asciimatics/widgets.py
- tests/test_widgets.py
#186 
Added a new RegEx option to the `FileBrowser` to allow filtering of files
If you need me to change anything, please let me know.
> RegEx filtering option for FileBrowser

- asciimatics/widgets.py
None
Improve performance of widget creation in Python 3 by slotting widgets.
> slot widgets for performance and memory improvment

- .travis.yml
- tests/test_effects.py
- tests/test_renderers.py
- tests/test_screen.py
> Skip tests that require a TTY when none is available - for #199

- asciimatics/parsers.py
- samples/credits.py
- tests/test_parsers.py
Sanitizing parsers #224 
Added parser to sanitize control codes
Fixed comments from last PR
> Control code parser

- doc/source/troubleshooting.rst
Updated instructions for emulating terminal in PyCharm Professional
> Added instructions for emulating terminal PyCharm

- asciimatics/widgets.py
- tests/test_widgets.py
Missing the options setter for DropdownList widget
> Added options setter for DropdownList

- CHANGES.rst
- asciimatics/widgets.py
- tests/test_widgets.py
Fix #270 - add nearest widget navigation.
> New navigation

- CHANGES.rst
- README.rst
Checks
------
_Before you go any further, please make sure that you have read the [contributing guidelines](https://asciimatics.readthedocs.io/en/latest/contributing.html), run the test suite and that your clone of this repository was taken after 18 October 2018.  (I had to fix up the git history and so clones before that date will have all sorts of merge issues)._ 
_Now please delete this pre-amble section and fill in the rest of the template..._
_Please list any Issues here_
_Please add any further information about the fix if it is not obvious from the related Issue above_
_If there is anything else you feel you need to add, please do so …
> Update for v1.12 release.

- asciimatics/widgets/listbox.py
#287 
Fix ListBox width overflow
> Fix ListBox width overflow.

- CHANGES.rst
- asciimatics/widgets/label.py
- tests/test_widgets.py
#303
Adds a name arg to Label's constructor
> Fixes #303 - Give Label constructor a name attribute

- samples/tab_demo.py
#271
Adds a sample app, does not change any widgets.
This app demonstrates how to use a row of Buttons to select
one of a handful of Frames to show; emulating a Tab page widget.
> Fix #271 - Added Tab sample app

- doc/source/troubleshooting.rst
No issues
THis is  doc fix
PyCharm Community is able to emulate terminal now
> docs: PyCharm Community now offers the terminal emulation option

- samples/maps.py
> Effect class is imported wrong, Fails to create cache files inside a new directory.

- CHANGES.rst
- asciimatics/widgets/textbox.py
- tests/test_widgets.py
#327
Adds ability to hide the cursor in TextBox and change scroll behaviour
> Hidecursor

- asciimatics/screen.py
- samples/credits.py
- tests/test_screen.py
Checks
------
https://github.com/peterbrittain/asciimatics/issues/340
When character is an utf-8 character - we are not mapping it to other special characters.
None
> utf-8 characters are not being mapped in the screen.py file

- doc/source/animation.rst
n/a, just something I noticed kicking the tires
fixes the acquisition of the event loop for Python 3.10+
n/a
> fix event loop for Python 3.10+

- tests/test_particles.py
Fixes #359
This avoids random failures in TestParticles.test_rain and TestParticles.test_drop_screen
This patch was done while working on reproducible builds for openSUSE.
> Fix random test failures
